name: Main

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          cache: 'npm'

      - name: Build
        run: npm ci

      - name: Test
        run: npm test

      - name: Generate Image Artifacts
        run: ./scripts/generate_screenshots.py
        uses: actions/upload-artifact@v4
        with:
          name: site-screenshots
          path: resources/*.png
